# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant Cassandra Project
# https://github.com/bcantoni/vagrant-cassandra
# Brian Cantoni

# This template sets up one or more VMs with DataStax Enterprise (DSE) installed.
# Set these environment variables before running `vagrant up`:
#   Optional:
#     DEB_CACHE_HOST = Debian package cache, e.g. "http://192.168.1.100:8000" (default: no cache)
#     VAGRANT_DSE_NODES = number of nodes to bring up (default: 2)
#   Required:
#     VAGRANT_DSE_USERNAME = username from DataStax registration
#     VAGRANT_DSE_PASSWORD = password from DataStax registration

# Adjustable settings
CFG_MEMSIZE = "3000"    # max memory for each VM
CFG_TZ = "US/Pacific"   # timezone, like US/Pacific, US/Eastern, UTC, Europe/Warsaw, etc.
NETWORK = '10.10.10.'   # base IP for DSE nodes
FIRST_IP = 10

# environment variable options
if ENV['VAGRANT_DSE_NODES']
  dse_nodes = ENV['VAGRANT_DSE_NODES'].to_i
else
  dse_nodes = 2
end

# if doing a vargrant up or reload, require to have the username password
if ARGV[0] == 'up' or ARGV[0] == 'reload'
  if ENV['VAGRANT_DSE_USERNAME']
    dse_username = ENV['VAGRANT_DSE_USERNAME']
  else
    abort ("Error: VAGRANT_DSE_USERNAME and VAGRANT_DSE_PASSWORD must be set with DataStax user credentials (register at datastax.com/register)")
  end

  if ENV['VAGRANT_DSE_PASSWORD']
    dse_password = ENV['VAGRANT_DSE_PASSWORD']
  else
    abort ("Error: VAGRANT_DSE_USERNAME and VAGRANT_DSE_PASSWORD must be set with DataStax user credentials (register at datastax.com/register)")
  end
end

# if local Debian proxy configured (DEB_CACHE_HOST), install and configure the proxy client
deb_cache_cmds = ""
if ENV['DEB_CACHE_HOST']
  deb_cache_host = ENV['DEB_CACHE_HOST']
  deb_cache_cmds = <<CACHE
apt-get install squid-deb-proxy-client -y
echo 'Acquire::http::Proxy "#{deb_cache_host}";' | sudo tee /etc/apt/apt.conf.d/30autoproxy
echo "Acquire::http::Proxy { debian.datastax.com DIRECT; };" | sudo tee -a /etc/apt/apt.conf.d/30autoproxy
cat /etc/apt/apt.conf.d/30autoproxy
CACHE
end


# Provisioning script for DSE nodes (dse0, dse1, ...)
# todo: better dynamic generation of /etc/hosts list
node_script = <<SCRIPT
#!/bin/bash
cat > /etc/hosts <<EOF
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

10.10.10.10   dse0
10.10.10.11   dse1
10.10.10.12   dse2
10.10.10.13   dse3
10.10.10.14   dse4
10.10.10.15   dse5
EOF

# set timezone
echo "#{CFG_TZ}" > /etc/timezone    
dpkg-reconfigure -f noninteractive tzdata

#{deb_cache_cmds}

# configure DataStax repository
echo "deb http://#{dse_username}:#{dse_password}@debian.datastax.com/enterprise stable main" | sudo tee -a /etc/apt/sources.list.d/datastax.sources.list
wget -q -O - http://debian.datastax.com/debian/repo_key | sudo apt-key add -
apt-get update

# install DSE, Java, and a few base packages
apt-get install vim curl zip unzip git python-pip openjdk-7-jdk dse-full -y

# configure DSE
echo "Configuring DataStax Enterprise"
sudo sed -i 's/- seeds:.*$/- seeds: dse0/'             /etc/dse/cassandra/cassandra.yaml
sudo sed -i 's/listen_address:.*$/listen_address: %s/' /etc/dse/cassandra/cassandra.yaml
sudo sed -i 's/rpc_address:.*$/rpc_address: 0.0.0.0/'  /etc/dse/cassandra/cassandra.yaml

# start DSE
echo "Starting DataStax Enterprise"
sudo service dse start

echo "Vagrant provisioning complete"
SCRIPT

# Configure VM servers
puts "Configured for #{dse_nodes} DSE node(s)"
servers = []
(0..dse_nodes-1).each do |i|
  name = 'dse' + i.to_s
  ip = NETWORK + (FIRST_IP + i).to_s
  servers << {'name' => name, 'ip' => ip}
end

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  servers.each do |server|
    config.vm.define server['name'] do |config2|
      config2.vm.hostname = server['name']
      server_ip = server['ip']
      config2.vm.network :private_network, ip: server_ip
      config2.vm.provision :shell, :inline => node_script % server_ip

      config2.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"]  = CFG_MEMSIZE
      end
      config2.vm.provider :virtualbox do |v|
        v.name = server['name']
        v.customize ["modifyvm", :id, "--memory", CFG_MEMSIZE]
      end

    end
  end
end
