# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant Cassandra Project
# https://github.com/bcantoni/vagrant-cassandra
# Brian Cantoni

# This sample sets up 1 VM ('base') with only Java installed.
# See the README for a walkthrough explaining Cassandra and DataStax installation.

# Adjustable settings
CFG_MEMSIZE = "3000"      # max memory for each VM
CFG_TZ = "US/Pacific"     # timezone, like US/Pacific, US/Eastern, UTC, Europe/Warsaw, etc.
CFG_IP = "10.211.54.100"  # private IP address

node_script = <<SCRIPT
#!/bin/bash

# set timezone
echo "#{CFG_TZ}" > /etc/timezone    
dpkg-reconfigure -f noninteractive tzdata

# install a few base packages
apt-get update
apt-get install vim curl python-pip -y

# install java
apt-get install openjdk-7-jre -y
SCRIPT


# VM configurations
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :base do |base|
    base.vm.box = "hashicorp/precise64"
    base.vm.provider "vmware_fusion" do |v|
      v.vmx["memsize"]  = CFG_MEMSIZE
    end
    base.vm.provider :virtualbox do |v|
      v.name = "base"
      v.customize ["modifyvm", :id, "--memory", CFG_MEMSIZE]
    end
    base.vm.network :private_network, ip: CFG_IP
    base.vm.hostname = "base"
    base.vm.provision :shell, :inline => node_script
  end
end
