# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant Cassandra Project
# https://github.com/bcantoni/vagrant-cassandra
# Brian Cantoni

# This sample sets up 1 VM ('cassandra') with only Java installed.
# See the README for a walkthrough explaining Cassandra and DataStax installation.

# Adjustable settings
CFG_MEMSIZE = "3000"      # max memory for each VM
CFG_TZ = "US/Pacific"     # timezone, like US/Pacific, US/Eastern, UTC, Europe/Warsaw, etc.
CFG_IP = "10.211.54.10"   # private IP address

node_script = <<SCRIPT
#!/bin/bash

# set timezone
echo "#{CFG_TZ}" > /etc/timezone    
dpkg-reconfigure -f noninteractive tzdata

# install and configure for local debian proxy (if present)
apt-get install squid-deb-proxy-client -y
echo 'Acquire::http::Proxy "http://10.211.54.100:8000/";' | sudo tee /etc/apt/apt.conf.d/30autoproxy

# install a few base packages
apt-get update
apt-get install vim curl python-pip -y

# install java
apt-get install openjdk-7-jre -y
SCRIPT


# VM configurations
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :cassandra do |x|
    x.vm.box = "hashicorp/precise64"
    x.vm.provider "vmware_fusion" do |v|
      v.vmx["memsize"]  = CFG_MEMSIZE
    end
    x.vm.provider :virtualbox do |v|
      v.name = "cassandra"
      v.customize ["modifyvm", :id, "--memory", CFG_MEMSIZE]
    end
    x.vm.network :private_network, ip: CFG_IP
    x.vm.hostname = "cassandra"
    x.vm.provision :shell, :inline => node_script
  end
end
