# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant Cassandra Project
# https://github.com/bcantoni/vagrant-cassandra
# Brian Cantoni

# This template sets up 6 VMs:
#   node11-16: Java plus Apache Cassandra installed
# See the README for a walkthrough explaining Cassandra and DataStax installation.

# Adjustable settings
CFG_MEMSIZE = "1400"    # max memory for each VM
CFG_TZ = "US/Pacific"   # timezone, like US/Pacific, US/Eastern, UTC, Europe/Warsaw, etc.
SERVER_COUNT = 4
NETWORK = '10.211.55.'
FIRST_IP = 110

# if local Debian proxy configured (DEB_CACHE_HOST), install and configure the proxy client
deb_cache_cmds = ""
if ENV['DEB_CACHE_HOST']
  deb_cache_host = ENV['DEB_CACHE_HOST']
  deb_cache_cmds = <<CACHE
apt-get install squid-deb-proxy-client -y
echo 'Acquire::http::Proxy "#{deb_cache_host}";' | sudo tee /etc/apt/apt.conf.d/30autoproxy
cat /etc/apt/apt.conf.d/30autoproxy
CACHE
end

# Provisioning script for Cassandra nodes (node11-16)
node_script = <<SCRIPT
#!/bin/bash
cat > /etc/hosts <<EOF
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

10.211.55.110   node10
10.211.55.111   node11
10.211.55.112   node12
10.211.55.113   node13
10.211.55.114   node14
10.211.55.115   node15
10.211.55.116   node16
EOF

# set timezone
echo "#{CFG_TZ}" > /etc/timezone    
dpkg-reconfigure -f noninteractive tzdata

#{deb_cache_cmds}

# configure Apache Cassandra and OpenJDK repos
echo "deb http://www.apache.org/dist/cassandra/debian 36x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
curl --silent https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
add-apt-repository ppa:openjdk-r/ppa
apt-get update

# install Java first, then Apache Cassandra
apt-get install openjdk-8-jdk -y
apt-get install vim curl zip unzip git python-pip cassandra -y

# stop Cassandra (which automatically starts after install) and clear data files
echo "Stopping Cassandra..."
sleep 5
service cassandra stop
sleep 5
rm -rf /var/lib/cassandra/*

# copy datacenter config files and restart Cassandra
IP=$(ifconfig | egrep -o 10\.211\.[0-9]{2}\.[0-9]{3} | head -n 1)
sed -i -e "s/^\s*cluster_name:.*$/cluster_name: 'MultiDC Vagrant'/" /etc/cassandra/cassandra.yaml
sed -i -e "s/ seeds:.*$/ seeds: 'node11,node12'/" /etc/cassandra/cassandra.yaml
sed -i -e "s/^listen_address:.*$/listen_address: $IP/" /etc/cassandra/cassandra.yaml
sed -i -e "s/^.*broadcast_address:.*$/broadcast_address: /" /etc/cassandra/cassandra.yaml
sed -i -e "s/^rpc_address:.*$/rpc_address: 0.0.0.0/" /etc/cassandra/cassandra.yaml
sed -i -e "s/^.*broadcast_rpc_address:.*$/broadcast_rpc_address: $IP/" /etc/cassandra/cassandra.yaml
sed -i -e "s/^endpoint_snitch:.*$/endpoint_snitch: PropertyFileSnitch/" /etc/cassandra/cassandra.yaml

cp /vagrant/cassandra-topology.properties /etc/cassandra
echo "Restarting Cassandra..."
service cassandra start

echo "Vagrant provisioning complete"
SCRIPT


# Configure VM servers
servers = []
(1..SERVER_COUNT).each do |i|
  name = 'node1' + i.to_s
  ip = NETWORK + (FIRST_IP + i).to_s
  servers << {'name' => name, 'ip' => ip}
end

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  servers.each do |server|
    config.vm.define server['name'] do |config2|
      config2.vm.hostname = server['name']
      config2.vm.network :private_network, ip: server['ip']

      config2.vm.provision :shell, :inline => node_script

      config2.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"]  = CFG_MEMSIZE
      end
      config2.vm.provider :virtualbox do |v|
        v.name = server['name']
        v.customize ["modifyvm", :id, "--memory", CFG_MEMSIZE]
      end

    end
  end
end
