# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant Cassandra Project
# https://github.com/bcantoni/vagrant-cassandra
# Brian Cantoni

# This template sets up 7 VMs:
#   node10: OpsCenter installed
#   node11-16: only Java installed
# See the README for a walkthrough explaining Cassandra and DataStax installation.

# Adjustable settings
CFG_MEMSIZE = "1500"    # max memory for each VM
CFG_TZ = "US/Pacific"   # timezone, like US/Pacific, US/Eastern, UTC, Europe/Warsaw, etc.
SERVER_COUNT = 7
NETWORK = '10.211.55.'
FIRST_IP = 110

# if local Debian proxy configured (DEB_CACHE_HOST), install and configure the proxy client
deb_cache_cmds = ""
if ENV['DEB_CACHE_HOST']
  deb_cache_host = ENV['DEB_CACHE_HOST']
  deb_cache_cmds = <<CACHE
apt-get install squid-deb-proxy-client -y
echo 'Acquire::http::Proxy "#{deb_cache_host}";' | sudo tee /etc/apt/apt.conf.d/30autoproxy
echo "Acquire::http::Proxy { debian.datastax.com DIRECT; };" | sudo tee -a /etc/apt/apt.conf.d/30autoproxy
cat /etc/apt/apt.conf.d/30autoproxy
CACHE
end

# Provisioning script for Opscenter node (node10)
opsc_script = <<SCRIPT
#!/bin/bash
cat > /etc/hosts <<EOF
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

10.211.55.110   node10
10.211.55.111   node11
10.211.55.112   node12
10.211.55.113   node13
10.211.55.114   node14
10.211.55.115   node15
10.211.55.116   node16
EOF

# set timezone
echo "#{CFG_TZ}" > /etc/timezone    
dpkg-reconfigure -f noninteractive tzdata

#{deb_cache_cmds}

# add DataStax repo for APT
echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/datastax.community.list
wget -q -O - http://debian.datastax.com/debian/repo_key | sudo apt-key add -
apt-get update

# install OpsCenter and a few base packages
apt-get install vim curl zip unzip git python-pip opscenter -y

# start OpsCenter
service opscenterd start

echo "Vagrant provisioning complete and OpsCenter started"
SCRIPT

# Provisioning script for Cassandra nodes (node11-16)
node_script = <<SCRIPT
#!/bin/bash
cat > /etc/hosts <<EOF
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

10.211.55.110   node10
10.211.55.111   node11
10.211.55.112   node12
10.211.55.113   node13
10.211.55.114   node14
10.211.55.115   node15
10.211.55.116   node16
EOF

# set timezone
echo "#{CFG_TZ}" > /etc/timezone    
dpkg-reconfigure -f noninteractive tzdata

#{deb_cache_cmds}

# configure DataStax repo
echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
wget -q -O - http://debian.datastax.com/debian/repo_key | sudo apt-key add -
apt-get update

# install Java first, then DataStax Community Edition
apt-get install openjdk-7-jdk libjna-java -y
apt-get install vim curl zip unzip git python-pip python-support dsc20 cassandra=2.0.11 datastax-agent -y

# stop Cassandra (which automatically starts after install) and clear data files
echo "Stopping Cassandra..."
service cassandra stop
rm -rf /var/lib/cassandra/data/system/*

# copy datacenter config files and restart Cassandra
cp /vagrant/cassandra.yaml /etc/cassandra
cp /vagrant/cassandra-topology.properties /etc/cassandra
echo "stomp_interface: 10.211.55.110" | sudo tee -a /var/lib/datastax-agent/conf/address.yaml
echo "Restarting Cassandra..."
service cassandra start
service datastax-agent restart

echo "Vagrant provisioning complete"
SCRIPT


# Configure VM servers
servers = []
(0..SERVER_COUNT-1).each do |i|
  name = 'node1' + i.to_s
  ip = NETWORK + (FIRST_IP + i).to_s
  servers << {'name' => name, 'ip' => ip}
end

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  servers.each do |server|
    config.vm.define server['name'] do |config2|
      config2.vm.hostname = server['name']
      config2.vm.network :private_network, ip: server['ip']

      if (server['name'] == 'node10')
        config2.vm.provision :shell, :inline => opsc_script
      else
        config2.vm.provision :shell, :inline => node_script
      end

      config2.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"]  = CFG_MEMSIZE
      end
      config2.vm.provider :virtualbox do |v|
        v.name = server['name']
        v.customize ["modifyvm", :id, "--memory", CFG_MEMSIZE]
      end

    end
  end
end
